//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FortuneTellingEntities : DbContext
    {
        public FortuneTellingEntities()
            : base("name=FortuneTellingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<Taiwanlunisolar> Taiwanlunisolar { get; set; }
        public virtual DbSet<VideoType> VideoType { get; set; }
        public virtual DbSet<WordLibrary> WordLibrary { get; set; }
        public virtual DbSet<WordLibraryUserInput> WordLibraryUserInput { get; set; }
        public virtual DbSet<Video> Video { get; set; }
    }
}
