//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.Resource.Share {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Branch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Branch() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fate.Resource.Share.Branch", typeof(Branch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 辰 的當地語系化字串。
        /// </summary>
        public static string Chen {
            get {
                return ResourceManager.GetString("Chen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 丑 的當地語系化字串。
        /// </summary>
        public static string Chou {
            get {
                return ResourceManager.GetString("Chou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 亥 的當地語系化字串。
        /// </summary>
        public static string Hai {
            get {
                return ResourceManager.GetString("Hai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卯 的當地語系化字串。
        /// </summary>
        public static string Mao {
            get {
                return ResourceManager.GetString("Mao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申 的當地語系化字串。
        /// </summary>
        public static string Shen {
            get {
                return ResourceManager.GetString("Shen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 巳 的當地語系化字串。
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未 的當地語系化字串。
        /// </summary>
        public static string Wei {
            get {
                return ResourceManager.GetString("Wei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 午 的當地語系化字串。
        /// </summary>
        public static string Wu {
            get {
                return ResourceManager.GetString("Wu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 戌 的當地語系化字串。
        /// </summary>
        public static string Xu {
            get {
                return ResourceManager.GetString("Xu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寅 的當地語系化字串。
        /// </summary>
        public static string Yin {
            get {
                return ResourceManager.GetString("Yin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 酉 的當地語系化字串。
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 子 的當地語系化字串。
        /// </summary>
        public static string Zi {
            get {
                return ResourceManager.GetString("Zi", resourceCulture);
            }
        }
    }
}
