//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.Resource.Operation {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ziwei {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ziwei() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fate.Resource.Operation.Ziwei", typeof(Ziwei).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 平 的當地語系化字串。
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 官祿宮 的當地語系化字串。
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 子女宮 的當地語系化字串。
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地劫 的當地語系化字串。
        /// </summary>
        public static string DiJie {
            get {
                return ResourceManager.GetString("DiJie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地空 的當地語系化字串。
        /// </summary>
        public static string DiKong {
            get {
                return ResourceManager.GetString("DiKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 土五局 的當地語系化字串。
        /// </summary>
        public static string EarthFive {
            get {
                return ResourceManager.GetString("EarthFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廟 的當地語系化字串。
        /// </summary>
        public static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 斐廉 的當地語系化字串。
        /// </summary>
        public static string FeiLian {
            get {
                return ResourceManager.GetString("FeiLian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 封誥 的當地語系化字串。
        /// </summary>
        public static string FengGqu {
            get {
                return ResourceManager.GetString("FengGqu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 火六局 的當地語系化字串。
        /// </summary>
        public static string FireSix {
            get {
                return ResourceManager.GetString("FireSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 交友宮 的當地語系化字串。
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地 的當地語系化字串。
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寡宿 的當地語系化字串。
        /// </summary>
        public static string GuaSu {
            get {
                return ResourceManager.GetString("GuaSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 孤辰 的當地語系化字串。
        /// </summary>
        public static string GuChen {
            get {
                return ResourceManager.GetString("GuChen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 福德宮 的當地語系化字串。
        /// </summary>
        public static string Happiness {
            get {
                return ResourceManager.GetString("Happiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 疾厄宮 的當地語系化字串。
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 華蓋 的當地語系化字串。
        /// </summary>
        public static string HuaGai {
            get {
                return ResourceManager.GetString("HuaGai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紅鸞 的當地語系化字串。
        /// </summary>
        public static string HungLuan {
            get {
                return ResourceManager.GetString("HungLuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 火星 的當地語系化字串。
        /// </summary>
        public static string HuoXing {
            get {
                return ResourceManager.GetString("HuoXing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 解神 的當地語系化字串。
        /// </summary>
        public static string JieShen {
            get {
                return ResourceManager.GetString("JieShen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 巨門 的當地語系化字串。
        /// </summary>
        public static string JuMen {
            get {
                return ResourceManager.GetString("JuMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廉貞 的當地語系化字串。
        /// </summary>
        public static string LianZhen {
            get {
                return ResourceManager.GetString("LianZhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 命宮 的當地語系化字串。
        /// </summary>
        public static string Life {
            get {
                return ResourceManager.GetString("Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 鈴星 的當地語系化字串。
        /// </summary>
        public static string LingXing {
            get {
                return ResourceManager.GetString("LingXing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 祿存 的當地語系化字串。
        /// </summary>
        public static string LuCun {
            get {
                return ResourceManager.GetString("LuCun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 龍池 的當地語系化字串。
        /// </summary>
        public static string LungChih {
            get {
                return ResourceManager.GetString("LungChih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 夫妻宮 的當地語系化字串。
        /// </summary>
        public static string Marriage {
            get {
                return ResourceManager.GetString("Marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金四局 的當地語系化字串。
        /// </summary>
        public static string MetalFour {
            get {
                return ResourceManager.GetString("MetalFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天馬 的當地語系化字串。
        /// </summary>
        public static string MingMa {
            get {
                return ResourceManager.GetString("MingMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 父母宮 的當地語系化字串。
        /// </summary>
        public static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 破軍 的當地語系化字串。
        /// </summary>
        public static string PoJun {
            get {
                return ResourceManager.GetString("PoJun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 破碎 的當地語系化字串。
        /// </summary>
        public static string PoSuei {
            get {
                return ResourceManager.GetString("PoSuei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 田宅宮 的當地語系化字串。
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 擎羊 的當地語系化字串。
        /// </summary>
        public static string QingYang {
            get {
                return ResourceManager.GetString("QingYang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 七殺 的當地語系化字串。
        /// </summary>
        public static string QuSha {
            get {
                return ResourceManager.GetString("QuSha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 咸池 的當地語系化字串。
        /// </summary>
        public static string ShianChih {
            get {
                return ResourceManager.GetString("ShianChih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兄弟宮 的當地語系化字串。
        /// </summary>
        public static string Siblings {
            get {
                return ResourceManager.GetString("Siblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 台輔 的當地語系化字串。
        /// </summary>
        public static string TaiFu {
            get {
                return ResourceManager.GetString("TaiFu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 太陽 的當地語系化字串。
        /// </summary>
        public static string TaiYang {
            get {
                return ResourceManager.GetString("TaiYang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 太陰 的當地語系化字串。
        /// </summary>
        public static string TaiYin {
            get {
                return ResourceManager.GetString("TaiYin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貪狼 的當地語系化字串。
        /// </summary>
        public static string TanLang {
            get {
                return ResourceManager.GetString("TanLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 陷 的當地語系化字串。
        /// </summary>
        public static string Terrible {
            get {
                return ResourceManager.GetString("Terrible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天府 的當地語系化字串。
        /// </summary>
        public static string TianFu {
            get {
                return ResourceManager.GetString("TianFu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天機 的當地語系化字串。
        /// </summary>
        public static string TianJi {
            get {
                return ResourceManager.GetString("TianJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天哭 的當地語系化字串。
        /// </summary>
        public static string TianKu {
            get {
                return ResourceManager.GetString("TianKu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天魁 的當地語系化字串。
        /// </summary>
        public static string TianKui {
            get {
                return ResourceManager.GetString("TianKui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天空 的當地語系化字串。
        /// </summary>
        public static string TianKung {
            get {
                return ResourceManager.GetString("TianKung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天梁 的當地語系化字串。
        /// </summary>
        public static string TianLiang {
            get {
                return ResourceManager.GetString("TianLiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天喜 的當地語系化字串。
        /// </summary>
        public static string TianShi {
            get {
                return ResourceManager.GetString("TianShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天虛 的當地語系化字串。
        /// </summary>
        public static string TianShiu {
            get {
                return ResourceManager.GetString("TianShiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天同 的當地語系化字串。
        /// </summary>
        public static string TianTong {
            get {
                return ResourceManager.GetString("TianTong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天巫 的當地語系化字串。
        /// </summary>
        public static string TianWu {
            get {
                return ResourceManager.GetString("TianWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天相 的當地語系化字串。
        /// </summary>
        public static string TianXiang {
            get {
                return ResourceManager.GetString("TianXiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天刑 的當地語系化字串。
        /// </summary>
        public static string TianXing {
            get {
                return ResourceManager.GetString("TianXing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天姚 的當地語系化字串。
        /// </summary>
        public static string TianYao {
            get {
                return ResourceManager.GetString("TianYao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天月 的當地語系化字串。
        /// </summary>
        public static string TianYue {
            get {
                return ResourceManager.GetString("TianYue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天鉞 的當地語系化字串。
        /// </summary>
        public static string TianYue_year {
            get {
                return ResourceManager.GetString("TianYue_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遷移宮 的當地語系化字串。
        /// </summary>
        public static string Travel {
            get {
                return ResourceManager.GetString("Travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 陀羅 的當地語系化字串。
        /// </summary>
        public static string TuoLuo {
            get {
                return ResourceManager.GetString("TuoLuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 落 的當地語系化字串。
        /// </summary>
        public static string VeryBad {
            get {
                return ResourceManager.GetString("VeryBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 旺 的當地語系化字串。
        /// </summary>
        public static string VeryGood {
            get {
                return ResourceManager.GetString("VeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 水二局 的當地語系化字串。
        /// </summary>
        public static string WaterTwo {
            get {
                return ResourceManager.GetString("WaterTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 財帛宮 的當地語系化字串。
        /// </summary>
        public static string Weealth {
            get {
                return ResourceManager.GetString("Weealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文昌 的當地語系化字串。
        /// </summary>
        public static string WenChang {
            get {
                return ResourceManager.GetString("WenChang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文曲 的當地語系化字串。
        /// </summary>
        public static string WenQu {
            get {
                return ResourceManager.GetString("WenQu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 木三局 的當地語系化字串。
        /// </summary>
        public static string WoodThree {
            get {
                return ResourceManager.GetString("WoodThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 武曲 的當地語系化字串。
        /// </summary>
        public static string WuQu {
            get {
                return ResourceManager.GetString("WuQu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 陰煞 的當地語系化字串。
        /// </summary>
        public static string YinSha {
            get {
                return ResourceManager.GetString("YinSha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 右弼 的當地語系化字串。
        /// </summary>
        public static string YouBu {
            get {
                return ResourceManager.GetString("YouBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 月馬 的當地語系化字串。
        /// </summary>
        public static string YueMa {
            get {
                return ResourceManager.GetString("YueMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紫微 的當地語系化字串。
        /// </summary>
        public static string ZiWei {
            get {
                return ResourceManager.GetString("ZiWei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 左輔 的當地語系化字串。
        /// </summary>
        public static string ZuoFu {
            get {
                return ResourceManager.GetString("ZuoFu", resourceCulture);
            }
        }
    }
}
